id: circleci-check-step
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Let's try to fix it, :instruction[can you tell me what's the error message?]"
        delay: 1000
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - package.json
      then:
        do:
        - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Oh.... why doesn't it find the package.json...."
              - delay: 2000
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Not sure that makes sense, can you try again?"
              - delay: 2000
