id: circleci-open-pr
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Seems everything is working, let's :codeInstruction[open a PR and commit our changes!]"
        delay: 1000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: github_pr_comment
            params:
              person: keen
              message: "Reviewing this right now, let's see..."
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_is_file_contains
              params:
                fileName: ".circleci/config.yml"
                regex: 'cd|prefix'
            then:
              do:
              - actionId: github_pr_reject
                params:
                  person: keen
                  message: "Checout all the prject and then travling in the directory might be buggy and maybe hurt caching, try another way" 
                  messageName: cd

            else:
              do:
               if:
                conditions:
                - conditionId: github_is_file_contains
                  params:
                    fileName: ".circleci/config.yml"
                    regex: 'working_directory'
                then:
                  do:
                  - actionId: github_pr_approve
                    params:
                      person: keen
                      message: "Approved! Go ahead and merge this PR. Quickly now."
                else:
                  do:
                  - actionId: github_pr_reject
                    params:
                      person: keen
                      message: "Seems like I'm missing how you made it work without setting the right working directory" 
                      messageName: working_directory
          
        github_pr_merged:
          do:
          - actionId: finish_step
