id: circleci-open-pr
hints:
  - "Try to use the `working_directory` property on your CircleCI config"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Seems everything is working, let's :codeInstruction[open a PR and commit our changes!]"
        delay: 1000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: github_pr_comment
            params:
              person: keen
              message: "Reviewing this right now, let's see..."
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_does_file_contain
              params:
                fileName: ".circleci/config.yml"
                regex: 'cd|prefix'
            then:
              do:
              - actionId: bot_message
                params:
                  person: keen
                  messages:
                    - text: "Checkout all the project and then traveling in the directory might be buggy and maybe hurt caching, try another way"
                      delay: 1300
              - actionId: github_pr_reject
                params:
                  person: keen
                  message: "Checkout all the project and then traveling in the directory might be buggy and maybe hurt caching, try another way"
                  messageName: cd

            else:
             if:
              conditions:
              - conditionId: github_does_file_contain
                params:
                  fileName: ".circleci/config.yml"
                  regex: 'working_directory'
              then:
                do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: "Approved! Go ahead and merge this PR. Quickly now."
                        delay: 1300
                - actionId: github_pr_approve
                  params:
                    person: keen
                    message: "Approved! Go ahead and merge this PR. Quickly now."
              else:
                do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: "Seems like I'm missing how you made it work without setting the right working directory."
                        delay: 1300
                - actionId: github_pr_reject
                  params:
                    person: keen
                    message: "Seems like I'm missing how you made it work without setting the right working directory."
                    messageName: working_directory

        github_pr_merged:
          do:
          - actionId: finish_step
